import { useState, useEffect } from "react";
import { X, CreditCard, Bitcoin, Shield, Lock, Check, ChevronRight, Wallet, QrCode, Copy } from "lucide-react";

export interface Campaign {
  id: string;
  title: string;
  subtitle: string;
  flag: string;
  description: string;
  needs: string[];
  needIcons: string[];
  progress: number;
  target: string;
  raised: string;
  beneficiaries: string;
  quote: string;
  color: string;
}

const cryptoOptions = [
  { key: "btc", name: "Bitcoin (BTC)", icon: "₿", color: "bg-orange-500/20 text-orange-400" },
  { key: "eth", name: "Ethereum (ETH)", icon: "Ξ", color: "bg-blue-500/20 text-blue-400" },
  { key: "usdttrc20", name: "USDT (TRC20)", icon: "₮", color: "bg-green-500/20 text-green-400" },
  { key: "usdc", name: "USDC", icon: "$", color: "bg-blue-600/20 text-blue-300" },
  { key: "sol", name: "Solana (SOL)", icon: "◎", color: "bg-purple-500/20 text-purple-400" },
  { key: "bnb", name: "BNB", icon: "◆", color: "bg-yellow-500/20 text-yellow-400" },
];

interface PaymentGatewayModalProps {
  campaign: Campaign;
  amount: number;
  donorName: string;
  isAnonymous: boolean;
  onClose: () => void;
  onSuccess: () => void;
  onBack: () => void;
  selectedCurrency: string;
}

export default function PaymentGatewayModal({
  campaign,
  amount,
  donorName,
  isAnonymous,
  selectedCurrency,
  onClose,
  onSuccess,
  onBack,
}: PaymentGatewayModalProps) {
  // isAnonymous is used for display purposes in production
  void isAnonymous;
  void donorName;

  const [paymentMethod, setPaymentMethod] = useState<"card" | "crypto" | null>(null);
  const [selectedCrypto, setSelectedCrypto] = useState<string | null>(null);
  const [message, setMessage] = useState<{
    type: "success" | "error";
    text: string;
  } | null>(null);
  const [cardDetails, setCardDetails] = useState({
    number: "",
    expiry: "",
    cvv: "",
    name: "",
  });
  const [isProcessing, setIsProcessing] = useState(false);
  const [showCryptoAddress, setShowCryptoAddress] = useState(false);
  const [cryptoAddress, setCryptoAddress] = useState("");
  const [cryptoAmount, setCryptoAmount] = useState("");
  const [paymentId, setPaymentId] = useState("");
  const [copied, setCopied] = useState(false);
  const [exchangeRate, setExchangeRate] = useState<number | null>(null);
  const handleCopyAddress = () => {
    navigator.clipboard.writeText(cryptoAddress);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  };
  useEffect(() => {
    if (selectedCurrency === "USD") return;
    const fetchExchangeRate = async () => {
      try {
        const response = await fetch(
          `https://api.exchangerate-api.com/v4/latest/${selectedCurrency}`
        );
        const data = await response.json();
        setExchangeRate(data.rates.USD);
      } catch (error) {
        console.error(error);
      }
    };
    fetchExchangeRate();
  }, [selectedCurrency]);

  const usdEquivalent = exchangeRate
    ? (amount * exchangeRate).toFixed(2)
    : null;
  const API_BASE =
    import.meta.env.VITE_API_URL || "http://localhost:5000";

  // Simulated crypto address (would be generated by backend in production)

  const handleCardSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      setIsProcessing(true);

      const response = await fetch(
        `${API_BASE}/create-checkout-session`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            amount,
            currency: selectedCurrency.toLowerCase(),
            campaignTitle: campaign.title,
          }),
        }
      );

      const data = await response.json();

      if (data.url) {
        window.location.href = data.url;
      } else {
        setMessage({
          type: "error",
          text: "Unable to start card payment. Please try again.",
        });
      }
    } catch (error) {
      console.error(error);
      setMessage({
        type: "error",
        text: "Something went wrong during payment.",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleCryptoSubmit = async () => {
    try {
      setIsProcessing(true);

      if (!selectedCrypto) {
        setMessage({
          type: "error",
          text: "Please select a cryptocurrency first.",
        });
        return;
      }

      const response = await fetch(
        `${API_BASE}/create-crypto-payment`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            amount,
            currency: selectedCurrency.toLowerCase(),
            coin: selectedCrypto,
          }),
        }
      );

      const data = await response.json();

      console.log(data);

      setCryptoAddress(data.pay_address);
      setCryptoAmount(data.pay_amount);
      setPaymentId(data.payment_id);
      setShowCryptoAddress(true);

    } catch (error) {
      console.error("Crypto payment error:", error);
      setMessage({
        type: "error",
        text: "Failed to generate crypto payment.",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const checkPaymentStatus = async (id: string) => {
    try {
      const response = await fetch(
        `${API_BASE}/check-crypto-payment/${id}`
      );

      const data = await response.json();

      console.log("Payment Status:", data.payment_status);

      if (data.payment_status === "finished") {
        onSuccess();
      }
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    if (!paymentId) return;

    const interval = setInterval(() => {
      checkPaymentStatus(paymentId);
    }, 10000);
    return () => clearInterval(interval);
  }, [paymentId]);
  const currencies = [
    // International
    { code: "USD", symbol: "$", label: "US Dollar" },
    { code: "EUR", symbol: "€", label: "Euro" },
    { code: "GBP", symbol: "£", label: "British Pound" },

    // Gulf / Arab Countries
    { code: "AED", symbol: "د.إ", label: "UAE Dirham" },
    { code: "SAR", symbol: "﷼", label: "Saudi Riyal" },
    { code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar" },
    { code: "QAR", symbol: "﷼", label: "Qatari Riyal" },
    { code: "BHD", symbol: ".د.ب", label: "Bahraini Dinar" },
    { code: "OMR", symbol: "﷼", label: "Omani Rial" },
    { code: "JOD", symbol: "د.ا", label: "Jordanian Dinar" },

    // Africa
    { code: "NGN", symbol: "₦", label: "Nigerian Naira" },
    { code: "EGP", symbol: "£", label: "Egyptian Pound" },
    { code: "ZAR", symbol: "R", label: "South African Rand" },

    // South Asia
    { code: "PKR", symbol: "₨", label: "Pakistani Rupee" },
    { code: "INR", symbol: "₹", label: "Indian Rupee" },
    { code: "BDT", symbol: "৳", label: "Bangladeshi Taka" },

    // Southeast Asia
    { code: "MYR", symbol: "RM", label: "Malaysian Ringgit" },
    { code: "IDR", symbol: "Rp", label: "Indonesian Rupiah" },
    { code: "TRY", symbol: "₺", label: "Turkish Lira" },
  ];
  const currentCurrency =
    currencies.find((c) => c.code === selectedCurrency) || currencies[0];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose} />

      <div className="relative bg-gradient-to-b from-emerald-900 to-slate-900 border border-amber-500/20 rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl shadow-amber-500/10 max-h-[90vh] overflow-y-auto">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-10 text-emerald-300/50 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="bg-gradient-to-r from-emerald-800/50 to-slate-800/50 p-6 border-b border-emerald-700/30">
          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              className="p-2 bg-emerald-800/50 hover:bg-emerald-700/50 rounded-lg transition-colors"
            >
              <ChevronRight className="w-4 h-4 text-emerald-200/60 rotate-180" />
            </button>
            <div>
              <h3 className="text-xl font-bold text-white">Complete Payment</h3>
              <p className="text-emerald-200/50 text-sm">
                {campaign.flag} {campaign.title} — {currentCurrency.symbol}{amount}
              </p>
            </div>
          </div>
        </div>

        <div className="p-6">
          {/* Modern Notification */}
          {message && (
            <div
              className={`mb-6 rounded-2xl border p-4 flex items-start gap-3 animate-in fade-in slide-in-from-top-2 duration-300 ${message.type === "success"
                ? "bg-green-500/10 border-green-500/20"
                : "bg-red-500/10 border-red-500/20"
                }`}
            >
              <div
                className={`w-10 h-10 rounded-xl flex items-center justify-center ${message.type === "success"
                  ? "bg-green-500/20"
                  : "bg-red-500/20"
                  }`}
              >
                {message.type === "success" ? (
                  <Check className="w-5 h-5 text-green-400" />
                ) : (
                  <X className="w-5 h-5 text-red-400" />
                )}
              </div>

              <div className="flex-1">
                <h5
                  className={`font-semibold ${message.type === "success"
                    ? "text-green-400"
                    : "text-red-400"
                    }`}
                >
                  {message.type === "success" ? "Success" : "Payment Error"}
                </h5>

                <p className="text-sm text-emerald-100/70 mt-1">
                  {message.text}
                </p>
              </div>

              <button
                onClick={() => setMessage(null)}
                className="text-emerald-200/40 hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          )}
          {!paymentMethod && !showCryptoAddress && (
            <>
              {/* Payment method selection */}
              <h4 className="text-white font-semibold mb-4">Choose Payment Method</h4>

              <div className="space-y-3 mb-6">
                {/* Card payment option */}
                <button
                  onClick={() => setPaymentMethod("card")}
                  className="w-full flex items-center gap-4 p-4 bg-emerald-800/30 border border-emerald-700/30 rounded-xl hover:border-amber-500/30 hover:bg-emerald-800/50 transition-all duration-300 text-left group"
                >
                  <div className="p-3 bg-blue-500/10 rounded-xl group-hover:bg-blue-500/20 transition-colors">
                    <CreditCard className="w-6 h-6 text-blue-400" />
                  </div>
                  <div className="flex-1">
                    <h5 className="text-white font-medium">Credit / Debit Card</h5>
                    <p className="text-emerald-200/50 text-sm">Visa, Mastercard, Amex & more</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="flex -space-x-1">
                      <div className="w-8 h-5 bg-blue-600 rounded text-white text-[8px] font-bold flex items-center justify-center">VISA</div>
                      <div className="w-8 h-5 bg-red-500 rounded text-white text-[8px] font-bold flex items-center justify-center">MC</div>
                    </div>
                    <ChevronRight className="w-4 h-4 text-emerald-200/30 group-hover:text-amber-400 transition-colors" />
                  </div>
                </button>

                {/* Crypto payment option */}
                <button
                  onClick={() => setPaymentMethod("crypto")}
                  className="w-full flex items-center gap-4 p-4 bg-emerald-800/30 border border-emerald-700/30 rounded-xl hover:border-amber-500/30 hover:bg-emerald-800/50 transition-all duration-300 text-left group"
                >
                  <div className="p-3 bg-orange-500/10 rounded-xl group-hover:bg-orange-500/20 transition-colors">
                    <Bitcoin className="w-6 h-6 text-orange-400" />
                  </div>
                  <div className="flex-1">
                    <h5 className="text-white font-medium">Cryptocurrency</h5>
                    <p className="text-emerald-200/50 text-sm">BTC, ETH, USDT, USDC & more</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="flex -space-x-1">
                      <div className="w-6 h-6 bg-orange-500 rounded-full text-white text-xs font-bold flex items-center justify-center">₿</div>
                      <div className="w-6 h-6 bg-blue-500 rounded-full text-white text-xs font-bold flex items-center justify-center">Ξ</div>
                    </div>
                    <ChevronRight className="w-4 h-4 text-emerald-200/30 group-hover:text-amber-400 transition-colors" />
                  </div>
                </button>
              </div>

              {/* Security badges */}
              <div className="flex items-center justify-center gap-4 text-emerald-200/40 text-xs">
                <div className="flex items-center gap-1">
                  <Shield className="w-3 h-3" />
                  <span>SSL Secured</span>
                </div>
                <div className="flex items-center gap-1">
                  <Lock className="w-3 h-3" />
                  <span>256-bit Encryption</span>
                </div>
              </div>
            </>
          )}

          {/* Card payment form */}
          {paymentMethod === "card" && !showCryptoAddress && (
            <form onSubmit={handleCardSubmit}>
              <h4 className="text-white font-semibold mb-4 flex items-center gap-2">
                <CreditCard className="w-5 h-5 text-blue-400" />
                Card Details
              </h4>

              <div className="space-y-4 mb-6">
                <div>
                  <label className="text-emerald-200/50 text-xs mb-2 block">Cardholder Name</label>
                  <input
                    type="text"
                    value={cardDetails.name}
                    onChange={(e) => setCardDetails({ ...cardDetails, name: e.target.value })}
                    placeholder="Mohammed Alafasy"
                    className="w-full bg-emerald-800/30 border border-emerald-700/30 rounded-xl px-4 py-3 text-white placeholder-emerald-400/30 focus:outline-none focus:border-amber-500/50 transition-colors"
                    required
                  />
                </div>

                <div>
                  <label className="text-emerald-200/50 text-xs mb-2 block">Card Number</label>
                  <input
                    type="text"
                    value={cardDetails.number}
                    onChange={(e) => {
                      const value = e.target.value.replace(/\D/g, "").slice(0, 16);
                      const formatted = value.replace(/(\d{4})(?=\d)/g, "$1 ");
                      setCardDetails({ ...cardDetails, number: formatted });
                    }}
                    placeholder="4242 4242 4242 4242"
                    className="w-full bg-emerald-800/30 border border-emerald-700/30 rounded-xl px-4 py-3 text-white placeholder-emerald-400/30 focus:outline-none focus:border-amber-500/50 transition-colors font-mono"
                    required
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-emerald-200/50 text-xs mb-2 block">Expiry Date</label>
                    <input
                      type="text"
                      value={cardDetails.expiry}
                      onChange={(e) => {
                        let value = e.target.value.replace(/\D/g, "").slice(0, 4);
                        if (value.length > 2) {
                          value = value.slice(0, 2) + "/" + value.slice(2);
                        }
                        setCardDetails({ ...cardDetails, expiry: value });
                      }}
                      placeholder="MM/YY"
                      className="w-full bg-emerald-800/30 border border-emerald-700/30 rounded-xl px-4 py-3 text-white placeholder-emerald-400/30 focus:outline-none focus:border-amber-500/50 transition-colors font-mono"
                      required
                    />
                  </div>
                  <div>
                    <label className="text-emerald-200/50 text-xs mb-2 block">CVV</label>
                    <input
                      type="text"
                      value={cardDetails.cvv}
                      onChange={(e) => setCardDetails({ ...cardDetails, cvv: e.target.value.replace(/\D/g, "").slice(0, 4) })}
                      placeholder="123"
                      className="w-full bg-emerald-800/30 border border-emerald-700/30 rounded-xl px-4 py-3 text-white placeholder-emerald-400/30 focus:outline-none focus:border-amber-500/50 transition-colors font-mono"
                      required
                    />
                  </div>
                </div>
              </div>

              {/* Payment summary */}
              <div className="bg-emerald-800/30 border border-emerald-700/30 rounded-xl p-4 mb-6">
                <div className="flex justify-between text-sm">
                  <span className="text-emerald-200/50">Amount</span>
                  <span className="text-amber-400 font-bold text-lg">{currentCurrency.symbol}{amount}</span>
                </div>
              </div>

              {/* Stripe badge */}
              <div className="flex items-center justify-center gap-2 text-emerald-200/30 text-xs mb-4">
                <Lock className="w-3 h-3" />
                <span>Payments processed securely by Flutterwave</span>
              </div>

              {/* Buttons */}
              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setPaymentMethod(null)}
                  className="flex-1 bg-emerald-800/50 hover:bg-emerald-700/50 text-emerald-200/70 font-medium py-3 rounded-xl transition-all duration-300 border border-emerald-700/30"
                >
                  Back
                </button>
                <button
                  type="submit"
                  disabled={isProcessing}
                  className="flex-1 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 disabled:opacity-50 disabled:cursor-not-allowed text-emerald-950 font-semibold py-3 rounded-xl transition-all duration-300 hover:shadow-lg hover:shadow-amber-500/25 flex items-center justify-center gap-2"
                >
                  {isProcessing ? (
                    <>
                      <div className="w-4 h-4 border-2 border-emerald-950/30 border-t-emerald-950 rounded-full animate-spin" />
                      Processing...
                    </>
                  ) : (
                    <>
                      <Lock className="w-4 h-4" />
                      Pay {currentCurrency.symbol}{amount}
                    </>
                  )}
                </button>
              </div>
            </form>
          )}

          {/* Crypto payment section */}
          {paymentMethod === "crypto" && !showCryptoAddress && (
            <div>
              <h4 className="text-white font-semibold mb-4 flex items-center gap-2">
                <Bitcoin className="w-5 h-5 text-orange-400" />
                Select Cryptocurrency
              </h4>

              <div className="grid grid-cols-2 gap-3 mb-6">
                {cryptoOptions.map((crypto) => (
                  <button
                    key={crypto.name}
                    onClick={() => setSelectedCrypto(crypto.key)}
                    className={`flex items-center gap-3 p-3 rounded-xl border transition-all duration-300 ${selectedCrypto === crypto.key
                      ? "border-amber-500/50 bg-amber-500/10"
                      : "border-emerald-700/30 bg-emerald-800/30 hover:border-emerald-600/50"
                      }`}
                  >
                    <div className={`w-10 h-10 rounded-lg flex items-center justify-center text-xl font-bold ${crypto.color}`}>
                      {crypto.icon}
                    </div>
                    <span className="text-white text-sm font-medium">{crypto.name.split(" ")[0]}</span>
                  </button>
                ))}
              </div>

              {/* Payment summary */}
              <div className="bg-emerald-800/30 border border-emerald-700/30 rounded-xl p-4 mb-6">

                {/* Amount */}
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-emerald-200/50">
                    Amount
                  </span>

                  <span className="text-amber-400 font-bold text-lg">
                    {currentCurrency.symbol}{amount}
                  </span>
                </div>

                {/* USD Equivalent */}
                {usdEquivalent && selectedCurrency !== "USD" && (
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-emerald-200/50">
                      USD Equivalent
                    </span>

                    <span className="text-emerald-200/80">
                      ≈ ${usdEquivalent}
                    </span>
                  </div>
                )}

                {/* Network */}
                <div className="flex justify-between text-sm">
                  <span className="text-emerald-200/50">
                    Network
                  </span>

                  <span className="text-emerald-200/70">
                    {cryptoOptions.find(c => c.key === selectedCrypto)?.name || "Select crypto"}
                  </span>
                </div>

              </div>

              {/* Coinbase badge */}
              <div className="flex items-center justify-center gap-2 text-emerald-200/30 text-xs mb-4">
                <Wallet className="w-3 h-3" />
                <span>Powered by Coinbase Commerce</span>
              </div>

              {/* Buttons */}
              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setPaymentMethod(null)}
                  className="flex-1 bg-emerald-800/50 hover:bg-emerald-700/50 text-emerald-200/70 font-medium py-3 rounded-xl transition-all duration-300 border border-emerald-700/30"
                >
                  Back
                </button>
                <button
                  onClick={handleCryptoSubmit}
                  disabled={!selectedCrypto || isProcessing}
                  className="flex-1 bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-400 hover:to-orange-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-3 rounded-xl transition-all duration-300 hover:shadow-lg hover:shadow-orange-500/25 flex items-center justify-center gap-2"
                >
                  {isProcessing ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Bitcoin className="w-4 h-4" />
                      Pay with Crypto
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* Crypto address display */}
          {showCryptoAddress && (
            <div className="text-center">
              <div className="inline-flex items-center justify-center mb-4">
                <div className="p-4 bg-green-500/20 rounded-full">
                  <QrCode className="w-8 h-8 text-green-400" />
                </div>
              </div>

              <h4 className="text-white font-bold text-xl mb-2">Scan to Pay</h4>
              <p className="text-emerald-200/60 text-sm mb-6">
                Send exactly{" "}
                <span className="text-amber-400 font-bold">
                  {cryptoAmount || "0"} {cryptoOptions.find((c) => c.key === selectedCrypto)?.name.split(" ")[0]}
                </span>{" "}
                ({currentCurrency.symbol}{amount} {selectedCurrency})
              </p>

              {/* QR Code placeholder */}
              <div className="bg-white p-4 rounded-2xl inline-block mb-6">
                <div className="w-40 h-40 bg-gray-100 flex items-center justify-center">
                  <img
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=bitcoin:${cryptoAddress}?amount=${amount}`}
                    alt="Crypto payment QR code"
                    className="w-full h-full"
                  />
                </div>
              </div>

              {/* Address */}
              <div className="bg-emerald-800/30 border border-emerald-700/30 rounded-xl p-4 mb-6">
                <p className="text-emerald-200/50 text-xs mb-2">Send to this address:</p>
                <div className="flex items-center gap-2">
                  <code className="flex-1 text-amber-400 text-sm font-mono break-all">{cryptoAddress}</code>
                  <button
                    onClick={handleCopyAddress}
                    className="p-2 bg-emerald-700/50 hover:bg-emerald-600/50 rounded-lg transition-colors"
                  >
                    {copied ? (
                      <Check className="w-4 h-4 text-green-400" />
                    ) : (
                      <Copy className="w-4 h-4 text-emerald-200/60" />
                    )}
                  </button>
                </div>
              </div>

              {/* Important notes */}
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-4 mb-6 text-left">
                <h5 className="text-amber-400 font-medium text-sm mb-2">Important Notes:</h5>
                <ul className="text-emerald-200/50 text-xs space-y-1">
                  <li>• Send only {selectedCrypto} to this address</li>
                  <li>• Payment will be confirmed after blockchain confirmation</li>
                  <li>• You will receive confirmation once verified</li>
                </ul>
              </div>

              <button
                onClick={onSuccess}
                className="w-full bg-gradient-to-r from-green-500 to-green-600 hover:from-green-400 hover:to-green-500 text-white font-semibold py-3 rounded-xl transition-all duration-300 flex items-center justify-center gap-2"
              >
                <Check className="w-5 h-5" />
                I've Completed the Payment
              </button>

              <button
                onClick={() => {
                  setShowCryptoAddress(false);
                  setPaymentMethod(null);
                }}
                className="w-full mt-3 text-emerald-200/50 hover:text-emerald-200/70 text-sm transition-colors"
              >
                Cancel and choose different method
              </button>
            </div>
          )}
        </div>
      </div>
    </div >
  );
}
